name: bayes_dip_test
channels:
  - defaults
  - astra-toolbox
dependencies:
  - astra-toolbox
  - pip
  - pip:
    - pytest
    - https://github.com/odlgroup/odl/archive/master.zip
    # other dependencies are installed by "pip install -e ." based on install_requires in setup.cfg
