name: bayes_dip_test
channels:
  - defaults
  - astra-toolbox
dependencies:
  - astra-toolbox
  - pip
  - pip:
    - torch>=1.12
    - torchvision
    - tensorboardx
    - scikit-image
    - imageio
    - opt_einsum
    - tqdm
    - gpytorch
    - pytest
    - functorch
    - https://github.com/odlgroup/odl/archive/master.zip
