name: Test bayes_dip

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.10"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda install -c astra-toolbox astra-toolbox
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Install bayes_dip
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          pytest tests/
